services:
  binaryvault_api:
    container_name: binaryvault_api
    image: pickbas/binaryvault:latest
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: PickBas
      DB_PASSWORD: password
      DB_URL: postgresql://postgres:5432/binaryvault
      SPRING_PROFILES_ACTIVE: docker
      AWS_SHARED_CREDENTIALS_FILE: /app/.aws/credentials
    volumes:
      - $HOME/.aws/credentials:/app/.aws/credentials
    restart: always
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: PickBas
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres:

